### ISSUE TITLE
unbound variable error

### ISSUE THREAD

**Issue by jy329** [okdj0201/legacy-replacements#1]
When I executed below command, I faced unbound variable error.

$ make setup INI_FILE=${INI_FILE}
../common/bin/setup.sh
../common/bin/setup.sh: line 3: $1: unbound variable
make: *** [setup] Error 1

##Tried
Delete -u from line 1 as below
`#!/bin/bash -u` -> `#!/bin/bash`

Then, faced another error
```
$ make setup INI_FILE=${INI_FILE}
../common/bin/setup.sh
../common/bin/setup.sh: line 12: cdp: command not found
../common/bin/setup.sh: line 12: ${INIT_FILE}: ambiguous redirect
cp: ./cdp: No such file or directory
make: *** [setup] Error 1
```

**Comment by okdj0201** [comment]
-u is required.
Please specify ${INI_FILE} in your environment. Like ``` $make setup INI_FILE=~/.bashrc```.
For Makefile issue, did some bug fix, current source wil work for you : )

**Comment by jy329** [comment]
Oh It works now. Thank you.
